import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Footer() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.footer_container}>
                <h2 className={styles.index_footer}>This App is created by <span className={styles.index_span}>Ryotaro</span></h2>
            </div>
        </>
    )
}
