import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Footer() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
            </Head>
            <div className={styles.footer_container}>
                <h2 className={styles.index_footer}><span className="material-symbols-outlined">
                    potted_plant
                </span>This App is created by <span className={styles.footer_span}>Ryotaro</span></h2>
            </div>
        </>
    )
}
