import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Footer from './Footer'

export default function PipeData() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <h2>塞ぎ板 厚み計算アプリ</h2>
                </div>
            </main>
            <Footer />
        </>
    )
}
