import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'


export default function WeightCalculation() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
            <h2>重量計算アプリ</h2>
            <Link href='/'><button>Topへ戻る</button></Link>
        </div>
      </main>
    </>
  )
}
