import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
            <Link href='/components/pipeData'><button>鋼管データ一覧表</button></Link>
            <Link href='/components/weightCalculation'><button>重量計算</button></Link>
        </div>
      </main>
    </>
  )
}
